### PR TITLE
1. Always evaluate skipif section, 2.Support xfail in SKIPIF sections

### LINKED ISSUE #52: Support xfail in SKIPIF sections
As of PHP 7.2.0 there is the possibility to dynamically mark tests as XFAIL, see https://github.com/php/php-src/commit/5cee9dfe9a479c15d08f66a4baca83ed4e7ed288. This should be supported by PFFT2 as well.

### PR DESCRIPTION
**Pull request by hollyhuiLi**
#close #52 #48 #47

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks! I agree that this optimization is generally fragile (for instance, a test case might [check for arbitrary extensions](https://github.com/php/pftt2/pull/57/files#diff-4ea02fedcb077fdc5e5a7d6ed35136c8L150)) and has bugs (for instance, [`&&` has higher priority than `||`](https://github.com/php/pftt2/pull/57/files#diff-4ea02fedcb077fdc5e5a7d6ed35136c8L133)), so that it's best to completely drop it, and just run the skipif section always, to avoid false positives and false negatives.

I think we should have a look at `AbtractPhptTestCaseRunner2` which appears to be unused, and such could be removed. And we should also have a look at `AbstractPhptTestCaseRunner::evalSkipIf()` which looks fragile as well.

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

Applied as fbf6589a25163f8ea175a3820a9858a145f1995c. Thanks.

**Comment by hollyhuiLi** [comment]
@cmb69 , I've looked at AbstractPhptTestCaseRunner::evalSkipIf(), where the output of execution of SKIPIF section been evaluated. Logically it does looks fragile but it basically covers all the extisting cases that SKIPIF has been written. I'm not sure if I have a better way to handle this.

**Comment by cmb69** [comment]
Thanks for looking into this @hollyhuiLi. If the method does what it's supposed to do, no need to change it. :)

**Comment by hollyhuiLi** [comment]
#close #44

**Pull request closed without merging**
