### PR TITLE
Clean out major files

### PR DESCRIPTION
**Pull request by lavturo**
Enabled a part to clean out major files from the test pack and modified a comparison between files and ext types.

### CODE REVIEW

**Comment by lavturo** [comment]
@weltling @hollyhuiLi Can you please check these? Very quick fix for this part. Will help for testing. 

I'm unsure why my last commit is a part of this one. I believe it was already part of another PR.

**Comment by weltling** [comment]
@lavturo same here, please rebase to master.

Thanks.

**Comment by lavturo** [comment]
@weltling Rebased it and now it's only 1 commit.

**Comment by weltling** [comment]
This looks like a reasonable fix. @hollyhuiLi if ok with you, lets merge it.

Thanks.

**Comment by hollyhuiLi** [comment]
> This looks like a reasonable fix. @hollyhuiLi if ok with you, lets merge it.
> Thanks.

it looks good to me. Thanks!

**Comment by weltling** [comment]
Merged, thanks!

Closes #18.

**Pull request closed without merging**
