### PR TITLE
setup: download and install VC12 for MySQL

### PR DESCRIPTION
**Pull request by hollyhuiLi**

### CODE REVIEW

**Comment by cmb69** [comment]
LGTM, thanks! (If we wanted to *optimize* here, we could only install the x86 VC 12 redist, since we always install the x86 MySQL server.)

**Comment by hollyhuiLi** [comment]
> LGTM, thanks! (If we wanted to _optimize_ here, we could only install the x86 VC 12 redist, since we always install the x86 MySQL server.)

Thanks @cmb69, I've made the changes to just install x86 VC 12 redist.

**Comment by cmb69** [comment]
Thanks @hollyhuiLi! Applied as eeac64204956c0a8d50212adfd8f69b8cb85d0f4.

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

Closing.

**Pull request closed without merging**
