### PR TITLE
Fixes #7: Replaced bundled source files with binaries

### LINKED ISSUE #7: Replace bundled sources by library jars
PFTT2 contains some bundled source files of other projects, see https://github.com/php/pftt2/tree/master/src. Those sources seem unpatched, so it would make sense to check, whether they can be replaced by the binary releases of the corresponding projects. That would make simplify the maintanence of PFTT2 itself and ease upgrading of dependency libraries.

Thanks.

### PR DESCRIPTION
**Pull request by lavturo**
@cmb69 @weltling Could you check through these files? I found some more jar files, so it took a while to figure out what needed to be changed. There were some errors about a file not being in the class path, so I had to **modify** some of the jar files. However, if this is the incorrect way to package the src files, then I can revert them. I just wanted to create this PR for some feedback. 

The only source files left that were not created by us are `javax.annotation` and `se.datadosen.component`.

### CODE REVIEW

**Comment by cmb69** [comment]
Thanks for the PR!

If I understand you correctly, you have patched some pre-built third-party jars. I think this should better be avoided. Instead we should either fix our code using these libraries, or if we actually have had patched libraries, stick with these for now (we should review those patches later, and decide how to deal with it on a case by case basis),

**Comment by lavturo** [comment]
The reason I made the modifications to the jar files was because there was always some methods missing or not working correctly. I was looking through some of the files that kept giving an error and found that previously, there were methods added or variables that were changed for pftt to work the way it works now. 

I could document the changes that were made within the jar files via the wiki or in a separate text file if that helps.

**Comment by cmb69** [comment]
Thanks for the explanation. I still wonder whether it makes sense to replace the patched sources with patched jar files at all. Anyhow, please provide a file that documents the required changes.

**Comment by lavturo** [comment]
@cmb69 Added the file to show which jar files were modified. It's a lot less than I thought, but that is probably because some of the source files were modified instead of the jar files. 

Some of the changes did not seem possible unless we were to change the source code completely.

**Comment by cmb69** [comment]
Okay, I think there are more urgent issues than deciding what to do with the email functionality in general, and the ristretto package in particular, so I'm going to merge this, but rename ristretto-1.0.jar to ristretto-1.0-1.jar to clarify that it is not the original jar.

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

Thanks! Applied as 6eab5a2f5a72424463b3bc1ebb95429e9d20ddc3.

**Pull request closed without merging**
