### PR TITLE
Evaluate whether the /doc folder is needed

### PR DESCRIPTION
**Pull request by hollyhuiLi**

### CODE REVIEW

**Comment by weltling** [comment]
@hollyhuiLi thanks for the PR. Could you rebase to master, please?

Thanks.

**Comment by hollyhuiLi** [comment]
@weltling It took me a while to research on how to rebase, especially on a fork. Now the pull request looks more clean. Thanks!

**Comment by weltling** [comment]
Thanks @hollyhuiLi. @lavturo ok from your side?

Thanks.

**Comment by lavturo** [comment]
@weltling Seems good to me.

**Comment by weltling** [comment]
Ok. I was just checking to merge this. In how far are the files remained in the `/doc` dir relevant? The `index.html` contains some old info and is misleading? I'm even not sure the GUI part ever works, it didn't last time I've tried. If it should be kept, probably the contents of it should be fixed. 

Regarding `ssh_server.fatjar` - what is it good for? Is it used somewhere? Couldn't find any use of that.

Thanks.

**Comment by hollyhuiLi** [comment]
I actually deleted all the documents under doc/apidoc sub-directory. I kept doc/index.html only because there were some old info there I thought we may reference some when we finally write the instruction document for the tool.
Regarding ssh_server.fatjar, my best guess is that it is used to hosting webservice for the document on a machine where pftt is installed. Never get it work though...

**Comment by weltling** [comment]
Oki doki, lets keep those old info files for now. Thanks for clarifying.

**Comment by weltling** [comment]
Merged as f110243fba1379413a205e3beb7e46623f496dc2. Thanks.

**Pull request closed without merging**
