### PR TITLE
Close #38: Add PHP 7.4 support

### LINKED ISSUE #13: Inspect PFTT2 console options
The options shown by `bin\pftt help` need to be inspected. The goal is to evaluate, which options work, which don't. Please put the findings in this issue. A further decision for every option should be made, whether it needs to be supported or removed.

Thanks.

### LINKED ISSUE #38: Add PHP 7.4 support

### PR DESCRIPTION
**Pull request by cmb69**

### CODE REVIEW

**Comment by weltling** [comment]
@lavturo @hollyhuiLi could you review and test please?

Thanks.

**Comment by lavturo** [comment]
@cmb69 I have one error when I try to run this with PHP-7.4.0 builds. It tells me an extension `wddx` is missing/not enabled. I'm not sure why this error occurs. I looked into a bit and saw that for previous version (7.3 and before), `wddx` is available/enabled. 

I am wondering if we need to check for `wddx` to test, if not, we can disable checking for that. Unless there's something specifically with PHP-7.4 that causes this?

**Comment by cmb69** [comment]
Thanks for checking! The wddx extension [has been unbundled](https://wiki.php.net/rfc/deprecate-and-remove-ext-wddx), and is no longer available in PHP 7.4 and up. So any special treatment of the wddx extension should be removed for PHP 7.4 testing. Not sure if the smoke test requirement should be dropped for all PHP versions.

**Comment by lavturo** [comment]
@cmb69 As discussed, if you're going to remove it from the smoke test, that will be here: [wddx](https://github.com/php/pftt2/blob/05e66bd4a07bb84e1190fc77ae9eb73e9534c958/src/com/mostc/pftt/model/smoke/RequiredExtensionsSmokeTest.java#L137). You could also check through the list to see if there are other extensions that do not need to be part of the smoke test.

**Comment by cmb69** [comment]
Thanks, @lavturo! I'll see to it. :)

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

Applied as 116120135b954beb0cdd316492af74a6eef67da8 and 1bb5ffcc657a36d2fcc14577e4d2e70e0ac1efd8.

Thanks!

**Pull request closed without merging**
