### PR TITLE
Close #8: Cleanup unused files in the /bin folder

### LINKED ISSUE #8: Cleanup unused files in the /bin folder

### PR DESCRIPTION
**Pull request by cmb69**
`cmp`, `diff`, `diff3`, `patch` and `sdiff` are Windows ports of the
respective Gnu utilities.  `NanoServerApiScan` is a Microsoft tool.
`handle` is from sysinternals.

Since none of these executables are used by PFTT, we can safely remove
them.

### CODE REVIEW

**Comment by cmb69** [comment]
I think that we also can remove `PFTT Shell.lnk` and `pftt_workspace.WEW`. The former is not portable and does not appear to be really useful (it starts pftt_shell in elevated mode, but uses hard-coded files names); the latter is likely a WinDbg saved workspace (looks doubtful that WinDbg is useful for running PFTT).

`7za`, `elevate`, `pskill` and `pssuspend`  are executed by PFTT, so they have to stay (at least for now).

The files without file extension are shell scripts; the `.cmd` files are Windows batch files (many of these just aliases). Not sure if all these are even supported, but for now it might make sense to stick with them, and remove extraneous files in a later phase. Regarding the shell scripts: it seems to me that PFTT2 is no longer compatible with other operating systems than Windows (if it ever has been), so removing them would make sense, if there are no plans to bring back support for other OSs.

**Comment by weltling** [comment]
PFTT could be configured to invoke WinDbg in case of a crash, not sure about directly but at least to create a crash dump. The saved state, do you mean it is needed to run Windbg?

The .lnk one is indeed useless.

Regarding the bash scripts - they're unmaintained. Please lets defer deleting them, though. There is no plan for now, but also no hurry.

Thanks.

**Comment by cmb69** [comment]
> The saved state, do you mean it is needed to run Windbg?

I opened the file in WinDbg, and it shows:
````
Win32 error 0n3: C:\php-sdk\php-5.5-src-re6bde1f\ext\date\lib\parse_tz.c
    "The system cannot find the path specified."
````
Apparently, this file is the result of a former debug session, and has been inadvertenly committed.

**Comment by cmb69** [comment]
Removed "PFTT Shell.lnk" and pftt_workspace.WEW. I think this PR is good to be merged now.

Thanks.

**Comment by weltling** [comment]
Yep, looks like nothing is blocking this PR.

Thanks.

**Comment by php-pulls** [comment]
**Comment on behalf of cmb at php.net:**

Applied as f6ddff3a4b96e4a36f2534ad4177900485538238.

Thanks!

**Pull request closed without merging**
